openapi: 3.0.0
info:
  title: Blog API
  description: Blog API Practice
  version: 0.0.1

servers:
  - url: http://localhost:8000
    description: 'ローカル環境'

tags:
  - name: 'users'
    description: 'ユーザーの操作'
  - name: 'articles'
    description: '記事の操作'
  - name: 'comments'
    description: 'コメントの操作'
  - name: 'nices'
    description: 'いいねの操作'

paths:
  /user:
    get:
      summary: 自身のユーザー情報を返す
      tags: ['users']
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/getUserResponse'
        '400':
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /user/{user_id}:
    put:
      summary: 指定したidのユーザー情報を変更する
      tags: ['users']
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/putUserRequest'
        required: true
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: 'SuccessResponse'
        '400':
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /token:
    get:
      summary: IDトークン、アクセストークン、リフレッシュトークンを取得する
      tags: ['users']
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getCallbackTokenRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
        '400':
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /regenearte_token:
    get:
      summary: IDトークン、アクセストークンを再取得
      tags: ['users']
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getRegenerateTokenRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
        '400':
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /article:
    post:
      summary: 記事を投稿する
      tags: ['articles']
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postArticleRequest'
        required: true
      responses:
        '200':
          description: 'SuccessResponse'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/article'
        '400':
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /article/list:
    get:
      summary: 記事一覧を取得する
      tags: ['articles']
      parameters:
        - in: query
          name: page
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'SuccessResponse'
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/getArticleListResponse'
        '400':
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /article/{article_id}:
    get:
      summary: 指定したidの記事詳細を取得
      tags: ['articles']
      parameters:
        - in: path
          name: article_id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: 'SuccessResponse'
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/article'
        '400':
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    put:
      summary: 指定したidの記事を変更する
      tags: ['articles']
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/putArticleRequest'
        required: true
      parameters:
        - in: path
          name: article_id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: 'SuccessResponse'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nullObject'
        '400':
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    delete:
      summary: 指定したidの記事を削除する
      tags: ['articles']
      parameters:
        - in: path
          name: article_id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: 'SuccessResponse'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nullObject'
        '400':
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /comment:
    post:
      summary: 指定した記事にコメントを登録する
      tags: ['comments']
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postCommentRequest'
        required: true
      responses:
        '200':
          description: 'SuccessResponse'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'
        '400':
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /comment/{comment_id}:
    put:
      summary: 指定したidの記事を変更する
      tags: ['comments']
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/putCommentRequest'
        required: true
      parameters:
        - in: path
          name: comment_id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: 'SuccessResponse'
        '400':
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    delete:
      summary: 指定したidのコメントを削除する
      tags: ['comments']
      parameters:
        - in: path
          name: comment_id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: 'SuccessResponse'
        '400':
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /nice:
    post:
      summary: 指定した記事にいいねを登録する
      tags: ['nices']
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postNiceRequest'
      responses:
        '200':
          description: 'SuccessResponse'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nice'
        '400':
          description: 'Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

components:
  schemas:
    user:
      type: object
      properties:
        user_id:
          type: integer
        google_id:
          type: integer
        user_name:
          type: string
        email:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
      required:
        - user_id
        - user_name
        - email
        - created_at
        - updated_at

    article:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        contents:
          type: string
        user_id:
          type: integer
        user_name:
          type: string
        nice_num:
          type: integer
        created_at:
          type: string
        updated_at:
          type: string
        comments:
          type: array
          items:
            $ref: '#/components/schemas/comment'
      required:
        - id
        - title
        - contents
        - user_id
        - user_name
        - created_at
        - updated_at

    comment:
      type: object
      properties:
        comment_id:
          type: number
        article_id:
          type: number
        user_id:
          type: number
        user_name:
          type: string
        message:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
      required:
        - comment_id
        - article_id
        - user_id
        - user_name
        - message
        - created_at
        - updated_at

    nice:
      type: object
      properties:
        nice_id:
          type: number
        article_id:
          type: number
        user_id:
          type: number

    token:
      type: object
      properties:
        id_token:
          type: string
        access_token:
          type: string
        refresh_token:
          type: string

    getUserResponse:
      type: object
      properties:
        user_id:
          type: number
        google_id:
          type: number
        user_name:
          type: string
        email:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
      required:
        - user_id
        - user_name
        - email
        - created_at
        - updated_at

    putUserRequest:
      type: object
      properties:
        user_name:
          type: string

    getCallbackTokenRequest:
      type: object
      properties:
        code:
          type: string
      required:
        - code

    getRegenerateTokenRequest:
      type: object
      properties:
        refresh_token:
          type: string
      required:
        - refresh_token

    postArticleRequest:
      type: object
      properties:
        title:
          type: string
        contents:
          type: string
        user_id:
          type: number
      required:
        - title
        - contents
        - user_id

    getArticleListResponse:
      type: array
      items:
        type: object
        $ref: '#/components/schemas/article'

    putArticleRequest:
      type: object
      properties:
        title:
          type: string
        contents:
          type: string

    postCommentRequest:
      type: object
      properties:
        article_id:
          type: number
        user_id:
          type: number
        message:
          type: string

    putCommentRequest:
      type: object
      properties:
        message:
          type: string

    postNiceRequest:
      type: object
      properties:
        article_id:
          type: number
        user_id:
          type: number
    postGoogleCallbackRequest:
      type: object
      properties:
        code:
          type: string
    error:
      type: object
      properties:
        ErrCode:
          type: string
        Message:
          type: string
    nullObject:
      type: object
      nullable: true
      example: null
